-- MySQL Script generated by MySQL Workbench
-- vie 17 abr 2020 16:32:35 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema unadsys
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `unadsys` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `unadsys` ;

-- -----------------------------------------------------
-- Table `unadsys`.`cara00config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara00config` (
  `cara00id` INT(11) NOT NULL,
  `cara00idperfilconsejero` INT(11) NULL DEFAULT '0',
  `cara00idperfillider` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`cara00id`),
  INDEX `cara00idperfilconsejero` (`cara00idperfilconsejero` ASC) VISIBLE,
  INDEX `cara00idperfillider` (`cara00idperfillider` ASC) VISIBLE,
  CONSTRAINT `cara00config_ibfk_1`
    FOREIGN KEY (`cara00idperfilconsejero`)
    REFERENCES `unadsys`.`unad05perfiles` (`unad05id`),
  CONSTRAINT `cara00config_ibfk_2`
    FOREIGN KEY (`cara00idperfillider`)
    REFERENCES `unadsys`.`unad05perfiles` (`unad05id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara01encuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara01encuesta` (
  `cara01idperaca` INT(11) NOT NULL,
  `cara01idtercero` INT(11) NOT NULL,
  `cara01id` INT(11) NOT NULL DEFAULT '0',
  `cara01completa` VARCHAR(1) NULL DEFAULT NULL,
  `cara01fichaper` INT(11) NULL DEFAULT '0',
  `cara01fichafam` INT(11) NULL DEFAULT '0',
  `cara01fichaaca` INT(11) NULL DEFAULT '0',
  `cara01fichalab` INT(11) NULL DEFAULT '0',
  `cara01fichabien` INT(11) NULL DEFAULT '0',
  `cara01fichapsico` INT(11) NULL DEFAULT '0',
  `cara01fichadigital` INT(11) NULL DEFAULT '0',
  `cara01fichalectura` INT(11) NULL DEFAULT '0',
  `cara01ficharazona` INT(11) NULL DEFAULT '0',
  `cara01fichaingles` INT(11) NULL DEFAULT '0',
  `cara01fechaencuesta` INT(11) NULL DEFAULT '0',
  `cara01agnos` INT(11) NULL DEFAULT '0',
  `cara01sexo` VARCHAR(1) NULL DEFAULT NULL,
  `cara01pais` VARCHAR(3) NULL DEFAULT NULL,
  `cara01depto` VARCHAR(5) NULL DEFAULT NULL,
  `cara01ciudad` VARCHAR(8) NULL DEFAULT NULL,
  `cara01nomciudad` VARCHAR(100) NULL DEFAULT NULL,
  `cara01direccion` VARCHAR(100) NULL DEFAULT NULL,
  `cara01estrato` INT(11) NULL DEFAULT '0',
  `cara01zonares` VARCHAR(1) NULL DEFAULT NULL,
  `cara01estcivil` VARCHAR(1) NULL DEFAULT NULL,
  `cara01nomcontacto` VARCHAR(100) NULL DEFAULT NULL,
  `cara01parentezcocontacto` VARCHAR(100) NULL DEFAULT NULL,
  `cara01celcontacto` VARCHAR(50) NULL DEFAULT NULL,
  `cara01correocontacto` VARCHAR(50) NULL DEFAULT NULL,
  `cara01idzona` INT(11) NULL DEFAULT '0',
  `cara01idcead` INT(11) NULL DEFAULT '0',
  `cara01matconvenio` VARCHAR(1) NULL DEFAULT NULL,
  `cara01raizal` VARCHAR(1) NULL DEFAULT NULL,
  `cara01palenquero` VARCHAR(1) NULL DEFAULT NULL,
  `cara01afrocolombiano` VARCHAR(1) NULL DEFAULT NULL,
  `cara01otracomunnegras` VARCHAR(1) NULL DEFAULT NULL,
  `cara01rom` VARCHAR(1) NULL DEFAULT NULL,
  `cara01indigenas` INT(11) NULL DEFAULT '0',
  `cara01victimadesplazado` VARCHAR(1) NULL DEFAULT NULL,
  `cara01idconfirmadesp` INT(11) NULL DEFAULT '0',
  `cara01fechaconfirmadesp` INT(11) NULL DEFAULT '0',
  `cara01victimaacr` VARCHAR(1) NULL DEFAULT NULL,
  `cara01idconfirmacr` INT(11) NULL DEFAULT '0',
  `cara01fechaconfirmacr` INT(11) NULL DEFAULT '0',
  `cara01inpecfuncionario` VARCHAR(1) NULL DEFAULT NULL,
  `cara01inpecrecluso` VARCHAR(1) NULL DEFAULT NULL,
  `cara01inpectiempocondena` INT(11) NULL DEFAULT '0',
  `cara01centroreclusion` INT(11) NULL DEFAULT '0',
  `cara01discsensorial` VARCHAR(1) NULL DEFAULT NULL,
  `cara01discfisica` VARCHAR(1) NULL DEFAULT NULL,
  `cara01disccognitiva` VARCHAR(1) NULL DEFAULT NULL,
  `cara01idconfirmadisc` INT(11) NULL DEFAULT '0',
  `cara01fechaconfirmadisc` INT(11) NULL DEFAULT '0',
  `cara01fam_tipovivienda` INT(11) NULL DEFAULT '0',
  `cara01fam_vivecon` INT(11) NULL DEFAULT '0',
  `cara01fam_numpersgrupofam` INT(11) NULL DEFAULT '0',
  `cara01fam_hijos` INT(11) NULL DEFAULT '0',
  `cara01fam_personasacargo` INT(11) NULL DEFAULT '0',
  `cara01fam_dependeecon` VARCHAR(1) NULL DEFAULT NULL,
  `cara01fam_escolaridadpadre` INT(11) NULL DEFAULT '0',
  `cara01fam_escolaridadmadre` INT(11) NULL DEFAULT '0',
  `cara01fam_numhermanos` INT(11) NULL DEFAULT '0',
  `cara01fam_posicionherm` INT(11) NULL DEFAULT '0',
  `cara01fam_familiaunad` VARCHAR(1) NULL DEFAULT NULL,
  `cara01acad_tipocolegio` INT(11) NULL DEFAULT '0',
  `cara01acad_modalidadbach` INT(11) NULL DEFAULT '0',
  `cara01acad_estudioprev` VARCHAR(1) NULL DEFAULT NULL,
  `cara01acad_ultnivelest` INT(11) NULL DEFAULT '0',
  `cara01acad_obtubodiploma` VARCHAR(1) NULL DEFAULT NULL,
  `cara01acad_hatomadovirtual` VARCHAR(1) NULL DEFAULT NULL,
  `cara01acad_tiemposinest` INT(11) NULL DEFAULT '0',
  `cara01acad_razonestudio` INT(11) NULL DEFAULT '0',
  `cara01acad_primeraopc` VARCHAR(1) NULL DEFAULT NULL,
  `cara01acad_programagusto` VARCHAR(250) NULL DEFAULT NULL,
  `cara01acad_razonunad` INT(11) NULL DEFAULT '0',
  `cara01campus_compescrito` VARCHAR(1) NULL DEFAULT NULL,
  `cara01campus_portatil` VARCHAR(1) NULL DEFAULT NULL,
  `cara01campus_tableta` VARCHAR(1) NULL DEFAULT NULL,
  `cara01campus_telefono` VARCHAR(1) NULL DEFAULT NULL,
  `cara01campus_energia` INT(11) NULL DEFAULT '0',
  `cara01campus_internetreside` INT(11) NULL DEFAULT '0',
  `cara01campus_expvirtual` VARCHAR(1) NULL DEFAULT NULL,
  `cara01campus_ofimatica` VARCHAR(1) NULL DEFAULT NULL,
  `cara01campus_foros` VARCHAR(1) NULL DEFAULT NULL,
  `cara01campus_conversiones` VARCHAR(1) NULL DEFAULT NULL,
  `cara01campus_usocorreo` INT(11) NULL DEFAULT '0',
  `cara01campus_aprendtexto` VARCHAR(1) NULL DEFAULT NULL,
  `cara01campus_aprendvideo` VARCHAR(1) NULL DEFAULT NULL,
  `cara01campus_aprendmapas` VARCHAR(1) NULL DEFAULT NULL,
  `cara01campus_aprendeanima` VARCHAR(1) NULL DEFAULT NULL,
  `cara01campus_mediocomunica` INT(11) NULL DEFAULT '0',
  `cara01lab_situacion` INT(11) NULL DEFAULT '0',
  `cara01lab_sector` INT(11) NULL DEFAULT '0',
  `cara01lab_caracterjuri` INT(11) NULL DEFAULT '0',
  `cara01lab_cargo` INT(11) NULL DEFAULT '0',
  `cara01lab_antiguedad` INT(11) NULL DEFAULT '0',
  `cara01lab_tipocontrato` INT(11) NULL DEFAULT '0',
  `cara01lab_rangoingreso` INT(11) NULL DEFAULT '0',
  `cara01lab_tiempoacadem` INT(11) NULL DEFAULT '0',
  `cara01lab_tipoempresa` INT(11) NULL DEFAULT '0',
  `cara01lab_tiempoindepen` INT(11) NULL DEFAULT '0',
  `cara01lab_debebusctrab` VARCHAR(1) NULL DEFAULT NULL,
  `cara01lab_origendinero` INT(11) NULL DEFAULT '0',
  `cara01bien_baloncesto` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_voleibol` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_futbolsala` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_artesmarc` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_tenisdemesa` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_ajedrez` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_juegosautoc` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_interesrepdeporte` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_deporteint` VARCHAR(200) NULL DEFAULT NULL,
  `cara01bien_teatro` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_danza` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_musica` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_circo` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_artplast` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_cuenteria` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_interesreparte` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_arteint` VARCHAR(200) NULL DEFAULT NULL,
  `cara01bien_interpreta` INT(11) NULL DEFAULT '0',
  `cara01bien_nivelinter` INT(11) NULL DEFAULT '0',
  `cara01bien_danza_mod` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_danza_clas` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_danza_cont` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_danza_folk` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_niveldanza` INT(11) NULL DEFAULT '0',
  `cara01bien_emprendedor` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_nombreemp` VARCHAR(200) NULL DEFAULT NULL,
  `cara01bien_capacempren` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_tipocapacita` VARCHAR(200) NULL DEFAULT NULL,
  `cara01bien_impvidasalud` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_estraautocuid` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_pv_personal` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_pv_familiar` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_pv_academ` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_pv_labora` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_pv_pareja` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_amb` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_amb_agu` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_amb_bom` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_amb_car` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_amb_info` VARCHAR(1) NULL DEFAULT NULL,
  `cara01bien_amb_temas` VARCHAR(200) NULL DEFAULT NULL,
  `cara01psico_costoemocion` INT(11) NULL DEFAULT '0',
  `cara01psico_reaccionimpre` INT(11) NULL DEFAULT '0',
  `cara01psico_estres` INT(11) NULL DEFAULT '0',
  `cara01psico_pocotiempo` INT(11) NULL DEFAULT '0',
  `cara01psico_actitudvida` INT(11) NULL DEFAULT '0',
  `cara01psico_duda` INT(11) NULL DEFAULT '0',
  `cara01psico_problemapers` INT(11) NULL DEFAULT '0',
  `cara01psico_satisfaccion` INT(11) NULL DEFAULT '0',
  `cara01psico_discusiones` INT(11) NULL DEFAULT '0',
  `cara01psico_atencion` INT(11) NULL DEFAULT '0',
  `cara01niveldigital` INT(11) NULL DEFAULT '0',
  `cara01nivellectura` INT(11) NULL DEFAULT '0',
  `cara01nivelrazona` INT(11) NULL DEFAULT '0',
  `cara01nivelingles` INT(11) NULL DEFAULT '0',
  `cara01idconsejero` INT(11) NULL DEFAULT '0',
  `cara01fechainicio` INT(11) NULL DEFAULT '0',
  `cara01telefono1` VARCHAR(20) NULL DEFAULT '',
  `cara01telefono2` VARCHAR(20) NULL DEFAULT '',
  `cara01correopersonal` VARCHAR(50) NULL DEFAULT '',
  `cara01idprograma` INT(11) NULL DEFAULT '0',
  `cara01idescuela` INT(11) NULL DEFAULT '0',
  `cara01fichabiolog` INT(11) NULL DEFAULT '0',
  `cara01nivelbiolog` INT(11) NULL DEFAULT '0',
  `cara01fichafisica` INT(11) NULL DEFAULT '0',
  `cara01nivelfisica` INT(11) NULL DEFAULT '0',
  `cara01fichaquimica` INT(11) NULL DEFAULT '0',
  `cara01nivelquimica` INT(11) NULL DEFAULT '0',
  `cara01tipocaracterizacion` INT(11) NULL DEFAULT '0',
  `cara01perayuda` INT(11) NULL DEFAULT '0',
  `cara01perotraayuda` VARCHAR(200) NULL DEFAULT '',
  `cara01discsensorialotra` VARCHAR(100) NULL DEFAULT '',
  `cara01discfisicaotra` VARCHAR(100) NULL DEFAULT '',
  `cara01disccognitivaotra` VARCHAR(100) NULL DEFAULT '',
  `cara01idcursocatedra` INT(11) NULL DEFAULT '0',
  `cara01idgrupocatedra` INT(11) NULL DEFAULT '0',
  `cara01factordescper` INT(11) NULL DEFAULT '0',
  `cara01factordescpsico` INT(11) NULL DEFAULT '0',
  `cara01factordescinsti` INT(11) NULL DEFAULT '0',
  `cara01factordescacad` INT(11) NULL DEFAULT '0',
  `cara01factordesc` INT(11) NULL DEFAULT '0',
  `cara01criteriodesc` INT(11) NULL DEFAULT '0',
  `cara01desertor` VARCHAR(1) NULL DEFAULT '',
  `cara01factorprincipaldesc` INT(11) NULL DEFAULT '0',
  `cara01psico_puntaje` INT(11) NULL DEFAULT '0',
  `cara01modoaginacion` INT(11) NULL DEFAULT '0',
  `cara01numacompanamentos` INT(11) NULL DEFAULT '0',
  `cara01idperiodoacompana` INT(11) NULL DEFAULT '0',
  `cara01fechacierreacom` INT(11) NULL DEFAULT '0',
  `cara01formaacomp` INT(11) NULL DEFAULT '0',
  `cara01factorriesgoacomp` INT(11) NULL DEFAULT '0',
  `cara01factorprincpermanencia` INT(11) NULL DEFAULT '0',
  `cara01discversion` INT(11) NULL DEFAULT '0',
  `cara01discv2sensorial` INT(11) NULL DEFAULT '0',
  `cara02discv2intelectura` INT(11) NULL DEFAULT '0',
  `cara02discv2fisica` INT(11) NULL DEFAULT '0',
  `cara02discv2psico` INT(11) NULL DEFAULT '0',
  `cara02discv2sistemica` INT(11) NULL DEFAULT '0',
  `cara02discv2sistemicaotro` VARCHAR(250) NULL DEFAULT '',
  `cara02discv2multiple` INT(11) NULL DEFAULT '0',
  `cara02discv2multipleotro` VARCHAR(250) NULL DEFAULT '',
  `cara02talentoexcepcional` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`cara01id`),
  UNIQUE INDEX `cara01encuesta_id` (`cara01idtercero` ASC, `cara01idperaca` ASC) VISIBLE,
  INDEX `cara01encuesta_cead` (`cara01idcead` ASC) VISIBLE,
  INDEX `cara01encuesta_completa` (`cara01completa` ASC) VISIBLE,
  INDEX `cara01encuesta_consejero` (`cara01idconsejero` ASC) VISIBLE,
  INDEX `fk_cara01encuesta_exte02per_aca1_idx` (`cara01idperaca` ASC) VISIBLE,
  INDEX `fk_cara01encuesta_unad18pais1_idx` (`cara01pais` ASC) VISIBLE,
  INDEX `fk_cara01encuesta_unad19depto1_idx` (`cara01depto` ASC) VISIBLE,
  INDEX `fk_cara01encuesta_unad20ciudad1_idx` (`cara01ciudad` ASC) VISIBLE,
  INDEX `fk_cara01encuesta_unad21estadocivil1_idx` (`cara01estcivil` ASC) VISIBLE,
  INDEX `fk_cara01encuesta_unad23zona1_idx` (`cara01idzona` ASC) VISIBLE,
  INDEX `fk_cara01encuesta_cara02indigenas1_idx` (`cara01indigenas` ASC) VISIBLE,
  INDEX `fk_cara01encuesta_cara03centroreclusion1_idx` (`cara01centroreclusion` ASC) VISIBLE,
  INDEX `fk_cara01encuesta_cara04razonestudio1_idx` (`cara01acad_razonestudio` ASC) VISIBLE,
  INDEX `fk_cara01encuesta_cara05razonunad1_idx` (`cara01acad_razonunad` ASC) VISIBLE,
  INDEX `fk_cara01encuesta_cara11tipocaract1_idx` (`cara01tipocaracterizacion` ASC) VISIBLE,
  INDEX `fk_cara01encuesta_cara14ayudaajuste1_idx` (`cara01perayuda` ASC) VISIBLE,
  INDEX `fk_cara01encuesta_cara15factordeserta1_idx` (`cara01criteriodesc` ASC) VISIBLE,
  INDEX `fk_cara01encuesta_cara15factordeserta2_idx` (`cara01factorprincipaldesc` ASC) VISIBLE,
  INDEX `fk_cara01encuesta_cara35factorpermanece1_idx` (`cara01factorprincpermanencia` ASC) VISIBLE,
  INDEX `fk_cara01encuesta_cara37discapacidades1_idx` (`cara01discv2sensorial` ASC) VISIBLE,
  INDEX `fk_cara01encuesta_cara37discapacidades2_idx` (`cara02discv2intelectura` ASC) VISIBLE,
  INDEX `fk_cara01encuesta_cara37discapacidades3_idx` (`cara02discv2fisica` ASC) VISIBLE,
  INDEX `fk_cara01encuesta_cara37discapacidades4_idx` (`cara02discv2psico` ASC) VISIBLE,
  INDEX `fk_cara01encuesta_cara38talentos1_idx` (`cara02talentoexcepcional` ASC) VISIBLE,
  CONSTRAINT `fk_cara01encuesta_exte02per_aca1`
    FOREIGN KEY (`cara01idperaca`)
    REFERENCES `unadsys`.`exte02per_aca` (`exte02id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_unad18pais1`
    FOREIGN KEY (`cara01pais`)
    REFERENCES `unadsys`.`unad18pais` (`unad18codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_unad19depto1`
    FOREIGN KEY (`cara01depto`)
    REFERENCES `unadsys`.`unad19depto` (`unad19codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_unad20ciudad1`
    FOREIGN KEY (`cara01ciudad`)
    REFERENCES `unadsys`.`unad20ciudad` (`unad20codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_unad21estadocivil1`
    FOREIGN KEY (`cara01estcivil`)
    REFERENCES `unadsys`.`unad21estadocivil` (`unad21codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_unad23zona1`
    FOREIGN KEY (`cara01idzona`)
    REFERENCES `unadsys`.`unad23zona` (`unad23id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_unad24sede1`
    FOREIGN KEY (`cara01idcead`)
    REFERENCES `unadsys`.`unad24sede` (`unad24id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_cara02indigenas1`
    FOREIGN KEY (`cara01indigenas`)
    REFERENCES `unadsys`.`cara02indigenas` (`cara02id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_cara03centroreclusion1`
    FOREIGN KEY (`cara01centroreclusion`)
    REFERENCES `unadsys`.`cara03centroreclusion` (`cara03id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_cara04razonestudio1`
    FOREIGN KEY (`cara01acad_razonestudio`)
    REFERENCES `unadsys`.`cara04razonestudio` (`cara04id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_cara05razonunad1`
    FOREIGN KEY (`cara01acad_razonunad`)
    REFERENCES `unadsys`.`cara05razonunad` (`cara05id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_cara11tipocaract1`
    FOREIGN KEY (`cara01tipocaracterizacion`)
    REFERENCES `unadsys`.`cara11tipocaract` (`cara11id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_cara14ayudaajuste1`
    FOREIGN KEY (`cara01perayuda`)
    REFERENCES `unadsys`.`cara14ayudaajuste` (`cara14id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_cara15factordeserta1`
    FOREIGN KEY (`cara01criteriodesc`)
    REFERENCES `unadsys`.`cara15factordeserta` (`cara15id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_cara15factordeserta2`
    FOREIGN KEY (`cara01factorprincipaldesc`)
    REFERENCES `unadsys`.`cara15factordeserta` (`cara15id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_cara35factorpermanece1`
    FOREIGN KEY (`cara01factorprincpermanencia`)
    REFERENCES `unadsys`.`cara35factorpermanece` (`cara35id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_cara37discapacidades1`
    FOREIGN KEY (`cara01discv2sensorial`)
    REFERENCES `unadsys`.`cara37discapacidades` (`cara37id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_cara37discapacidades2`
    FOREIGN KEY (`cara02discv2intelectura`)
    REFERENCES `unadsys`.`cara37discapacidades` (`cara37id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_cara37discapacidades3`
    FOREIGN KEY (`cara02discv2fisica`)
    REFERENCES `unadsys`.`cara37discapacidades` (`cara37id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_cara37discapacidades4`
    FOREIGN KEY (`cara02discv2psico`)
    REFERENCES `unadsys`.`cara37discapacidades` (`cara37id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_cara38talentos1`
    FOREIGN KEY (`cara02talentoexcepcional`)
    REFERENCES `unadsys`.`cara38talentos` (`cara38id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_cara13consejeros1`
    FOREIGN KEY (`cara01idconsejero`)
    REFERENCES `unadsys`.`cara13consejeros` (`cara13idconsejero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_unad21estadocivil2`
    FOREIGN KEY (`cara01estcivil`)
    REFERENCES `unadsys`.`unad21estadocivil` (`unad21id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara01encuesta_cara13consejeros2`
    FOREIGN KEY (`cara01idconsejero`)
    REFERENCES `unadsys`.`cara13consejeros` (`cara13id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara02indigenas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara02indigenas` (
  `cara02consec` INT(11) NOT NULL,
  `cara02id` INT(11) NOT NULL DEFAULT '0',
  `cara02nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`cara02id`),
  UNIQUE INDEX `cara02indigenas_id` (`cara02consec` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara03centroreclusion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara03centroreclusion` (
  `cara03consec` INT(11) NOT NULL,
  `cara03id` INT(11) NOT NULL DEFAULT '0',
  `cara03nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`cara03id`),
  UNIQUE INDEX `cara03centroreclusion_id` (`cara03consec` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara04razonestudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara04razonestudio` (
  `cara04consec` INT(11) NOT NULL,
  `cara04id` INT(11) NOT NULL DEFAULT '0',
  `cara04activo` VARCHAR(1) NULL DEFAULT NULL,
  `cara04orden` INT(11) NULL DEFAULT '0',
  `cara04nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`cara04id`),
  UNIQUE INDEX `cara04razonestudio_id` (`cara04consec` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara05razonunad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara05razonunad` (
  `cara05consec` INT(11) NOT NULL,
  `cara05id` INT(11) NOT NULL DEFAULT '0',
  `cara05activo` VARCHAR(1) NULL DEFAULT NULL,
  `cara05orden` INT(11) NULL DEFAULT '0',
  `cara05nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`cara05id`),
  UNIQUE INDEX `cara05razonunad_id` (`cara05consec` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara06grupopreg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara06grupopreg` (
  `cara05consec` INT(11) NOT NULL,
  `cara06id` INT(11) NOT NULL DEFAULT '0',
  `cara06idgrupo` INT(11) NULL DEFAULT '0',
  `cara06nombre` VARCHAR(100) NULL DEFAULT NULL,
  `cara06cuerpo` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`cara06id`),
  UNIQUE INDEX `cara06grupopreg_id` (`cara05consec` ASC) VISIBLE,
  INDEX `fk_cara06grupopreg_cara07bloqueeval1_idx` (`cara06idgrupo` ASC) VISIBLE,
  CONSTRAINT `fk_cara06grupopreg_cara07bloqueeval1`
    FOREIGN KEY (`cara06idgrupo`)
    REFERENCES `unadsys`.`cara07bloqueeval` (`cara07id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara07bloqueeval`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara07bloqueeval` (
  `cara07id` INT(11) NOT NULL,
  `cara07nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`cara07id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara08pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara08pregunta` (
  `cara08idbloque` INT(11) NOT NULL,
  `cara08consec` INT(11) NOT NULL,
  `cara08id` INT(11) NOT NULL DEFAULT '0',
  `cara08activa` VARCHAR(1) NULL DEFAULT NULL,
  `cara08idgrupo` INT(11) NULL DEFAULT '0',
  `cara08titulo` VARCHAR(100) NULL DEFAULT NULL,
  `cara08cuerpo` TEXT NULL DEFAULT NULL,
  `cara08tipopreg` INT(11) NULL DEFAULT '0',
  `cara08usosiniciales` INT(11) NULL DEFAULT '0',
  `cara08usostotales` INT(11) NULL DEFAULT '0',
  `cara08nivelpregunta` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`cara08id`),
  UNIQUE INDEX `cara08pregunta_id` (`cara08idbloque` ASC, `cara08consec` ASC) VISIBLE,
  INDEX `fk_cara08pregunta_cara06grupopreg1_idx` (`cara08idgrupo` ASC) VISIBLE,
  CONSTRAINT `fk_cara08pregunta_cara06grupopreg1`
    FOREIGN KEY (`cara08idgrupo`)
    REFERENCES `unadsys`.`cara06grupopreg` (`cara06id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara09pregrpta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara09pregrpta` (
  `cara09idpregunta` INT(11) NOT NULL,
  `cara09consec` INT(11) NOT NULL,
  `cara09id` INT(11) NULL DEFAULT '0',
  `cara09valor` INT(11) NULL DEFAULT '0',
  `cara09contenido` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`cara09idpregunta`, `cara09consec`),
  INDEX `cara09pregrpta_padre` (`cara09idpregunta` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara10pregprueba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara10pregprueba` (
  `cara10idcara` INT(11) NOT NULL,
  `cara10idbloque` INT(11) NOT NULL,
  `cara10consec` INT(11) NOT NULL,
  `cara10id` INT(11) NOT NULL DEFAULT '0',
  `cara10idpregunta` INT(11) NULL DEFAULT '0',
  `cara10idrpta` INT(11) NULL DEFAULT '0',
  `cara10puntaje` INT(11) NULL DEFAULT '0',
  `cara10nivelpregunta` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`cara10id`),
  UNIQUE INDEX `cara10pregprueba_id` (`cara10idcara` ASC, `cara10idbloque` ASC, `cara10consec` ASC) VISIBLE,
  INDEX `cara10pregprueba_padre` (`cara10idcara` ASC) VISIBLE,
  INDEX `fk_cara10pregprueba_cara07bloqueeval1_idx` (`cara10idbloque` ASC) VISIBLE,
  INDEX `fk_cara10pregprueba_cara08pregunta1_idx` (`cara10idpregunta` ASC) VISIBLE,
  CONSTRAINT `fk_cara10pregprueba_cara07bloqueeval1`
    FOREIGN KEY (`cara10idbloque`)
    REFERENCES `unadsys`.`cara07bloqueeval` (`cara07id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara10pregprueba_cara08pregunta1`
    FOREIGN KEY (`cara10idpregunta`)
    REFERENCES `unadsys`.`cara08pregunta` (`cara08id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara11tipocaract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara11tipocaract` (
  `cara11consec` INT(11) NOT NULL,
  `cara11id` INT(11) NOT NULL DEFAULT '0',
  `cara11nombre` VARCHAR(100) NULL DEFAULT NULL,
  `cara11ficha1` VARCHAR(1) NULL DEFAULT NULL,
  `cara11ficha1pregbas` INT(11) NULL DEFAULT '0',
  `cara11ficha1pregprof` INT(11) NULL DEFAULT '0',
  `cara11ficha2` VARCHAR(1) NULL DEFAULT NULL,
  `cara11ficha2pregbas` INT(11) NULL DEFAULT '0',
  `cara11ficha2pregprof` INT(11) NULL DEFAULT '0',
  `cara11ficha3` VARCHAR(1) NULL DEFAULT NULL,
  `cara11ficha3pregbas` INT(11) NULL DEFAULT '0',
  `cara11ficha3pregprof` INT(11) NULL DEFAULT '0',
  `cara11ficha4` VARCHAR(1) NULL DEFAULT NULL,
  `cara11ficha4pregbas` INT(11) NULL DEFAULT '0',
  `cara11ficha4pregprof` INT(11) NULL DEFAULT '0',
  `cara11ficha5` VARCHAR(1) NULL DEFAULT NULL,
  `cara11ficha5pregbas` INT(11) NULL DEFAULT '0',
  `cara11ficha5pregprof` INT(11) NULL DEFAULT '0',
  `cara11ficha6` VARCHAR(1) NULL DEFAULT NULL,
  `cara11ficha6pregbas` INT(11) NULL DEFAULT '0',
  `cara11ficha6pregprof` INT(11) NULL DEFAULT '0',
  `cara11ficha7` VARCHAR(1) NULL DEFAULT NULL,
  `cara11ficha7pregbas` INT(11) NULL DEFAULT '0',
  `cara11ficha7pregprof` INT(11) NULL DEFAULT '0',
  `cara11fichabase` VARCHAR(1) NULL DEFAULT 'S',
  `cara11fichafamilia` VARCHAR(1) NULL DEFAULT 'S',
  PRIMARY KEY (`cara11id`),
  UNIQUE INDEX `cara11tipocaract_id` (`cara11consec` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara13consejeros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara13consejeros` (
  `cara13peraca` INT(11) NOT NULL,
  `cara13idconsejero` INT(11) NOT NULL,
  `cara13id` INT(11) NOT NULL DEFAULT '0',
  `cara13activo` VARCHAR(1) NULL DEFAULT NULL,
  `cara01idzona` INT(11) NULL DEFAULT '0',
  `cara01idcead` INT(11) NULL DEFAULT '0',
  `cara01cargaasignada` INT(11) NULL DEFAULT '0',
  `cara01cargafinal` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`cara13id`),
  UNIQUE INDEX `cara13consejeros_id` (`cara13peraca` ASC, `cara13idconsejero` ASC) VISIBLE,
  INDEX `fk_cara13consejeros_unad23zona1_idx` (`cara01idzona` ASC) VISIBLE,
  INDEX `fk_cara13consejeros_unad24sede1_idx` (`cara01idcead` ASC) VISIBLE,
  CONSTRAINT `fk_cara13consejeros_exte02per_aca1`
    FOREIGN KEY (`cara13peraca`)
    REFERENCES `unadsys`.`exte02per_aca` (`exte02id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara13consejeros_unad23zona1`
    FOREIGN KEY (`cara01idzona`)
    REFERENCES `unadsys`.`unad23zona` (`unad23id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara13consejeros_unad24sede1`
    FOREIGN KEY (`cara01idcead`)
    REFERENCES `unadsys`.`unad24sede` (`unad24id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara14ayudaajuste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara14ayudaajuste` (
  `cara14consec` INT(11) NOT NULL,
  `cara14id` INT(11) NOT NULL DEFAULT '0',
  `cara14activa` VARCHAR(1) NULL DEFAULT NULL,
  `cara14orden` INT(11) NULL DEFAULT '0',
  `cara14nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`cara14id`),
  UNIQUE INDEX `cara14ayudaajuste_id` (`cara14consec` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara15factordeserta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara15factordeserta` (
  `cara15consec` INT(11) NOT NULL,
  `cara15id` INT(11) NOT NULL DEFAULT '0',
  `cara15activa` VARCHAR(1) NULL DEFAULT NULL,
  `cara15orden` INT(11) NULL DEFAULT '0',
  `cara15nombre` VARCHAR(100) NULL DEFAULT NULL,
  `cara15grupo` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`cara15id`),
  UNIQUE INDEX `cara15factordeserta_id` (`cara15consec` ASC) VISIBLE,
  INDEX `fk_cara15factordeserta_cara22gruposfactores1_idx` (`cara15grupo` ASC) VISIBLE,
  CONSTRAINT `fk_cara15factordeserta_cara22gruposfactores1`
    FOREIGN KEY (`cara15grupo`)
    REFERENCES `unadsys`.`cara22gruposfactores` (`cara22id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara17preganexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara17preganexo` (
  `cara17idpregunta` INT(11) NOT NULL,
  `cara17consec` INT(11) NOT NULL,
  `cara17id` INT(11) NOT NULL DEFAULT '0',
  `cara17idorigen` INT(11) NULL DEFAULT '0',
  `cara17idanexo` INT(11) NULL DEFAULT '0',
  `cara17nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`cara17id`),
  UNIQUE INDEX `cara17preganexo_id` (`cara17idpregunta` ASC, `cara17consec` ASC) VISIBLE,
  INDEX `cara17preganexo_padre` (`cara17idpregunta` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara21lidereszona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara21lidereszona` (
  `cara21idlider` INT(11) NOT NULL,
  `cara21id` INT(11) NOT NULL DEFAULT '0',
  `cara21activo` VARCHAR(1) NULL DEFAULT NULL,
  `cara21idzona` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`cara21id`),
  UNIQUE INDEX `cara21lidereszona_id` (`cara21idlider` ASC) VISIBLE,
  INDEX `fk_cara21lidereszona_unad23zona1_idx` (`cara21idzona` ASC) VISIBLE,
  CONSTRAINT `fk_cara21lidereszona_unad23zona1`
    FOREIGN KEY (`cara21idzona`)
    REFERENCES `unadsys`.`unad23zona` (`unad23id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara22gruposfactores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara22gruposfactores` (
  `cara22id` INT(11) NOT NULL,
  `cara22nombre` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`cara22id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara23acompanamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara23acompanamento` (
  `cara23idtercero` INT(11) NOT NULL,
  `cara23idencuesta` INT(11) NOT NULL,
  `cara23consec` INT(11) NOT NULL,
  `cara23id` INT(11) NOT NULL DEFAULT '0',
  `cara23idtipo` INT(11) NULL DEFAULT '0',
  `cara23estado` INT(11) NULL DEFAULT '0',
  `cara23asisteinduccion` INT(11) NULL DEFAULT '0',
  `cara23asisteinmersioncv` INT(11) NULL DEFAULT '0',
  `cara23catedra_skype` INT(11) NULL DEFAULT '0',
  `cara23catedra_bler1` INT(11) NULL DEFAULT '0',
  `cara23catedra_bler2` INT(11) NULL DEFAULT '0',
  `cara23catedra_webconf` INT(11) NULL DEFAULT '0',
  `cara23catedra_avance` INT(11) NULL DEFAULT '0',
  `cara23catedra_criterio` INT(11) NULL DEFAULT '0',
  `cara23catedra_acciones` INT(11) NULL DEFAULT '0',
  `cara23catedra_resultados` INT(11) NULL DEFAULT '0',
  `cara23catedra_segprev` TEXT NULL DEFAULT NULL,
  `cara23cursos_total` INT(11) NULL DEFAULT '0',
  `cara23cursos_siningre` INT(11) NULL DEFAULT '0',
  `cara23cursos_porcing` DECIMAL(15,2) NULL DEFAULT '0.00',
  `cara23cursos_menor200` INT(11) NULL DEFAULT '0',
  `cara23cursos_porcperdida` DECIMAL(15,2) NULL DEFAULT '0.00',
  `cara23cursos_criterio` INT(11) NULL DEFAULT '0',
  `cara23cursos_otros` TEXT NULL DEFAULT NULL,
  `cara23cursos_accionlider` TEXT NULL DEFAULT NULL,
  `cara23aler_sociodem` TEXT NULL DEFAULT NULL,
  `cara23aler_psico` TEXT NULL DEFAULT NULL,
  `cara23aler_academ` TEXT NULL DEFAULT NULL,
  `cara23aler_econom` TEXT NULL DEFAULT NULL,
  `cara23aler_externo` TEXT NULL DEFAULT NULL,
  `cara23aler_interno` TEXT NULL DEFAULT NULL,
  `cara23aler_nivel` TEXT NULL DEFAULT NULL,
  `cara23aler_criterio` INT(11) NULL DEFAULT '0',
  `cara23comp_digital` INT(11) NULL DEFAULT '0',
  `cara23comp_cuanti` INT(11) NULL DEFAULT '0',
  `cara23comp_lectora` INT(11) NULL DEFAULT '0',
  `cara23comp_ingles` INT(11) NULL DEFAULT '0',
  `cara23comp_criterio` INT(11) NULL DEFAULT '0',
  `cara23nivela_digital` INT(11) NULL DEFAULT '0',
  `cara23nivela_cuanti` INT(11) NULL DEFAULT '0',
  `cara23nivela_lecto` INT(11) NULL DEFAULT '0',
  `cara23nivela_ingles` INT(11) NULL DEFAULT '0',
  `cara23nivela_exito` INT(11) NULL DEFAULT '0',
  `cara23contacto_efectivo` INT(11) NULL DEFAULT '0',
  `cara23contacto_forma` INT(11) NULL DEFAULT '0',
  `cara23contacto_observa` TEXT NULL DEFAULT NULL,
  `cara23aplaza` INT(11) NULL DEFAULT '0',
  `cara23seretira` INT(11) NULL DEFAULT '0',
  `cara23factorriesgo` INT(11) NULL DEFAULT '0',
  `cara23zonal_retro` TEXT NULL DEFAULT NULL,
  `cara23zonal_fecha` INT(11) NULL DEFAULT '0',
  `cara23zonal_idlider` INT(11) NULL DEFAULT '0',
  `cara23fecha` INT(11) NULL DEFAULT '0',
  `cara23cursos_ac1` INT(11) NULL DEFAULT '-1',
  `cara23cursos_ac2` INT(11) NULL DEFAULT '-1',
  `cara23cursos_ac3` INT(11) NULL DEFAULT '-1',
  `cara23cursos_ac4` INT(11) NULL DEFAULT '-1',
  `cara23cursos_ac5` INT(11) NULL DEFAULT '-1',
  `cara23cursos_ac6` INT(11) NULL DEFAULT '-1',
  `cara23cursos_ac7` INT(11) NULL DEFAULT '-1',
  `cara23cursos_ac8` INT(11) NULL DEFAULT '-1',
  `cara23cursos_ac9` INT(11) NULL DEFAULT '-1',
  `cara23catedra_aprueba` INT(11) NULL DEFAULT '-1',
  `cara23permanece` INT(11) NULL DEFAULT '-1',
  PRIMARY KEY (`cara23id`),
  UNIQUE INDEX `cara23acompanamento_id` (`cara23idencuesta` ASC, `cara23consec` ASC) VISIBLE,
  INDEX `fk_cara23acompanamento_cara24avancecatedra1_idx` (`cara23catedra_avance` ASC) VISIBLE,
  INDEX `fk_cara23acompanamento_cara25accionescat1_idx` (`cara23catedra_acciones` ASC) VISIBLE,
  INDEX `fk_cara23acompanamento_cara26resultcat1_idx` (`cara23catedra_resultados` ASC) VISIBLE,
  INDEX `fk_cara23acompanamento_cara27mediocont1_idx` (`cara23contacto_forma` ASC) VISIBLE,
  CONSTRAINT `fk_cara23acompanamento_cara01encuesta1`
    FOREIGN KEY (`cara23idencuesta`)
    REFERENCES `unadsys`.`cara01encuesta` (`cara01id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara23acompanamento_cara24avancecatedra1`
    FOREIGN KEY (`cara23catedra_avance`)
    REFERENCES `unadsys`.`cara24avancecatedra` (`cara24id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara23acompanamento_cara25accionescat1`
    FOREIGN KEY (`cara23catedra_acciones`)
    REFERENCES `unadsys`.`cara25accionescat` (`cara25id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara23acompanamento_cara26resultcat1`
    FOREIGN KEY (`cara23catedra_resultados`)
    REFERENCES `unadsys`.`cara26resultcat` (`cara26id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara23acompanamento_cara27mediocont1`
    FOREIGN KEY (`cara23contacto_forma`)
    REFERENCES `unadsys`.`cara27mediocont` (`cara27id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara23acompanamentoanterior`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara23acompanamentoanterior` (
  `cara23idtercero` INT(11) NOT NULL,
  `cara23idencuesta` INT(11) NOT NULL,
  `cara23consec` INT(11) NOT NULL,
  `cara23id` INT(11) NOT NULL DEFAULT '0',
  `cara23idtipo` INT(11) NULL DEFAULT '0',
  `cara23estado` INT(11) NULL DEFAULT '0',
  `cara23asisteinduccion` INT(11) NULL DEFAULT '0',
  `cara23asisteinmersioncv` INT(11) NULL DEFAULT '0',
  `cara23catedra_skype` INT(11) NULL DEFAULT '0',
  `cara23catedra_bler1` INT(11) NULL DEFAULT '0',
  `cara23catedra_bler2` INT(11) NULL DEFAULT '0',
  `cara23catedra_webconf` INT(11) NULL DEFAULT '0',
  `cara23catedra_avance` INT(11) NULL DEFAULT '0',
  `cara23catedra_criterio` INT(11) NULL DEFAULT '0',
  `cara23catedra_acciones` INT(11) NULL DEFAULT '0',
  `cara23catedra_resultados` INT(11) NULL DEFAULT '0',
  `cara23catedra_segprev` TEXT NULL DEFAULT NULL,
  `cara23cursos_total` INT(11) NULL DEFAULT '0',
  `cara23cursos_siningre` INT(11) NULL DEFAULT '0',
  `cara23cursos_porcing` DECIMAL(15,2) NULL DEFAULT '0.00',
  `cara23cursos_menor200` INT(11) NULL DEFAULT '0',
  `cara23cursos_porcperdida` DECIMAL(15,2) NULL DEFAULT '0.00',
  `cara23cursos_criterio` INT(11) NULL DEFAULT '0',
  `cara23cursos_otros` TEXT NULL DEFAULT NULL,
  `cara23cursos_accionlider` TEXT NULL DEFAULT NULL,
  `cara23aler_sociodem` TEXT NULL DEFAULT NULL,
  `cara23aler_psico` TEXT NULL DEFAULT NULL,
  `cara23aler_academ` TEXT NULL DEFAULT NULL,
  `cara23aler_econom` TEXT NULL DEFAULT NULL,
  `cara23aler_externo` TEXT NULL DEFAULT NULL,
  `cara23aler_interno` TEXT NULL DEFAULT NULL,
  `cara23aler_nivel` TEXT NULL DEFAULT NULL,
  `cara23aler_criterio` INT(11) NULL DEFAULT '0',
  `cara23comp_digital` INT(11) NULL DEFAULT '0',
  `cara23comp_cuanti` INT(11) NULL DEFAULT '0',
  `cara23comp_lectora` INT(11) NULL DEFAULT '0',
  `cara23comp_ingles` INT(11) NULL DEFAULT '0',
  `cara23comp_criterio` INT(11) NULL DEFAULT '0',
  `cara23nivela_digital` INT(11) NULL DEFAULT '0',
  `cara23nivela_cuanti` INT(11) NULL DEFAULT '0',
  `cara23nivela_lecto` INT(11) NULL DEFAULT '0',
  `cara23nivela_ingles` INT(11) NULL DEFAULT '0',
  `cara23nivela_exito` INT(11) NULL DEFAULT '0',
  `cara23contacto_efectivo` INT(11) NULL DEFAULT '0',
  `cara23contacto_forma` INT(11) NULL DEFAULT '0',
  `cara23contacto_observa` TEXT NULL DEFAULT NULL,
  `cara23aplaza` INT(11) NULL DEFAULT '0',
  `cara23seretira` INT(11) NULL DEFAULT '0',
  `cara23factorriesgo` INT(11) NULL DEFAULT '0',
  `cara23zonal_retro` TEXT NULL DEFAULT NULL,
  `cara23zonal_fecha` INT(11) NULL DEFAULT '0',
  `cara23zonal_idlider` INT(11) NULL DEFAULT '0',
  `cara23fecha` INT(11) NULL DEFAULT '0',
  `cara23cursos_ac1` INT(11) NULL DEFAULT '-1',
  `cara23cursos_ac2` INT(11) NULL DEFAULT '-1',
  `cara23cursos_ac3` INT(11) NULL DEFAULT '-1',
  `cara23cursos_ac4` INT(11) NULL DEFAULT '-1',
  `cara23cursos_ac5` INT(11) NULL DEFAULT '-1',
  `cara23cursos_ac6` INT(11) NULL DEFAULT '-1',
  `cara23cursos_ac7` INT(11) NULL DEFAULT '-1',
  `cara23cursos_ac8` INT(11) NULL DEFAULT '-1',
  `cara23cursos_ac9` INT(11) NULL DEFAULT '-1',
  `cara23catedra_aprueba` INT(11) NULL DEFAULT '-1',
  `cara23permanece` INT(11) NULL DEFAULT '-1',
  PRIMARY KEY (`cara23id`),
  UNIQUE INDEX `cara23acompanamento_id` (`cara23idencuesta` ASC, `cara23consec` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara24avancecatedra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara24avancecatedra` (
  `cara24consec` INT(11) NOT NULL,
  `cara24id` INT(11) NOT NULL DEFAULT '0',
  `cara24orden` INT(11) NULL DEFAULT '0',
  `cara24jornada` INT(11) NULL DEFAULT '0',
  `cara24activa` VARCHAR(1) NULL DEFAULT NULL,
  `cara24titulo` VARCHAR(100) NULL DEFAULT NULL,
  `cara24vrriesgo` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`cara24id`),
  UNIQUE INDEX `cara24avancecatedra_id` (`cara24consec` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara25accionescat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara25accionescat` (
  `cara25consec` INT(11) NOT NULL,
  `cara25id` INT(11) NOT NULL DEFAULT '0',
  `cara25orden` INT(11) NULL DEFAULT '0',
  `cara25activa` VARCHAR(1) NULL DEFAULT NULL,
  `cara25titulo` VARCHAR(100) NULL DEFAULT NULL,
  `cara25puntaje` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`cara25id`),
  UNIQUE INDEX `cara25accionescat_id` (`cara25consec` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara26resultcat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara26resultcat` (
  `cara26consec` INT(11) NOT NULL,
  `cara26id` INT(11) NOT NULL DEFAULT '0',
  `cara26orden` INT(11) NULL DEFAULT '0',
  `cara26activa` VARCHAR(1) NULL DEFAULT NULL,
  `cara26titulo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`cara26id`),
  UNIQUE INDEX `cara26resultcat_id` (`cara26consec` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara27mediocont`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara27mediocont` (
  `cara27consec` INT(11) NOT NULL,
  `cara27id` INT(11) NOT NULL DEFAULT '0',
  `cara27orden` INT(11) NULL DEFAULT '0',
  `cara27activa` VARCHAR(1) NULL DEFAULT NULL,
  `cara27titulo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`cara27id`),
  UNIQUE INDEX `cara27mediocont_id` (`cara27consec` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara28actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara28actividades` (
  `cara28consec` INT(11) NOT NULL,
  `cara28id` INT(11) NOT NULL DEFAULT '0',
  `cara28tipoactividad` INT(11) NULL DEFAULT '0',
  `cara28estado` INT(11) NULL DEFAULT '0',
  `cara28fecha` INT(11) NULL DEFAULT '0',
  `cara28horaini` INT(11) NULL DEFAULT '0',
  `cara28minini` INT(11) NULL DEFAULT '0',
  `cara28horafin` INT(11) NULL DEFAULT '0',
  `cara28minfin` INT(11) NULL DEFAULT '0',
  `cara28idresponsable` INT(11) NULL DEFAULT '0',
  `cara28idzona` INT(11) NULL DEFAULT '0',
  `cara28idcentro` INT(11) NULL DEFAULT '0',
  `cara28lugar` VARCHAR(200) NULL DEFAULT NULL,
  `cara28detalle` TEXT NULL DEFAULT NULL,
  `cara28formato` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`cara28id`),
  UNIQUE INDEX `cara28actividades_id` (`cara28consec` ASC) VISIBLE,
  INDEX `fk_cara28actividades_unad23zona1_idx` (`cara28idzona` ASC) VISIBLE,
  INDEX `fk_cara28actividades_unad24sede1_idx` (`cara28idcentro` ASC) VISIBLE,
  INDEX `fk_cara28actividades_cara30tipoactividad1_idx` (`cara28tipoactividad` ASC) VISIBLE,
  INDEX `fk_cara28actividades_cara32estadoactividad1_idx` (`cara28estado` ASC) VISIBLE,
  CONSTRAINT `fk_cara28actividades_unad23zona1`
    FOREIGN KEY (`cara28idzona`)
    REFERENCES `unadsys`.`unad23zona` (`unad23id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara28actividades_unad24sede1`
    FOREIGN KEY (`cara28idcentro`)
    REFERENCES `unadsys`.`unad24sede` (`unad24id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara28actividades_cara30tipoactividad1`
    FOREIGN KEY (`cara28tipoactividad`)
    REFERENCES `unadsys`.`cara30tipoactividad` (`cara30id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cara28actividades_cara32estadoactividad1`
    FOREIGN KEY (`cara28estado`)
    REFERENCES `unadsys`.`cara32estadoactividad` (`cara32id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara29actividadasiste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara29actividadasiste` (
  `cara29idactividad` INT(11) NOT NULL,
  `cara29idtercero` INT(11) NOT NULL,
  `cara29id` INT(11) NOT NULL DEFAULT '0',
  `cara29estado` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`cara29id`),
  UNIQUE INDEX `cara29actividadasiste_id` (`cara29idactividad` ASC, `cara29idtercero` ASC) VISIBLE,
  INDEX `cara29actividadasiste_padre` (`cara29idactividad` ASC) VISIBLE,
  INDEX `fk_cara29actividadasiste_cara31estadoasiste1_idx` (`cara29estado` ASC) VISIBLE,
  CONSTRAINT `fk_cara29actividadasiste_cara31estadoasiste1`
    FOREIGN KEY (`cara29estado`)
    REFERENCES `unadsys`.`cara31estadoasiste` (`cara31id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara30tipoactividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara30tipoactividad` (
  `cara30id` INT(11) NOT NULL,
  `cara30nombre` VARCHAR(100) NULL DEFAULT NULL,
  `cara30activa` INT(11) NULL DEFAULT '1',
  PRIMARY KEY (`cara30id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara31estadoasiste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara31estadoasiste` (
  `cara31id` INT(11) NOT NULL,
  `cara31nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`cara31id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara32estadoactividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara32estadoactividad` (
  `cara32id` INT(11) NOT NULL,
  `cara32nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`cara32id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara35factorpermanece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara35factorpermanece` (
  `cara35consec` INT(11) NOT NULL,
  `cara35id` INT(11) NOT NULL DEFAULT '0',
  `cara35activa` VARCHAR(1) NULL DEFAULT NULL,
  `cara35orden` INT(11) NULL DEFAULT '0',
  `cara35nombre` VARCHAR(100) NULL DEFAULT NULL,
  `cara35grupo` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`cara35id`),
  UNIQUE INDEX `cara35factorpermanece_id` (`cara35consec` ASC) VISIBLE,
  INDEX `fk_cara35factorpermanece_cara22gruposfactores1_idx` (`cara35grupo` ASC) VISIBLE,
  CONSTRAINT `fk_cara35factorpermanece_cara22gruposfactores1`
    FOREIGN KEY (`cara35grupo`)
    REFERENCES `unadsys`.`cara22gruposfactores` (`cara22id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara36tipodisc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara36tipodisc` (
  `cara36id` INT(11) NOT NULL,
  `cara36nombre` VARCHAR(50) NULL DEFAULT NULL,
  `cara36version` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`cara36id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara37discapacidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara37discapacidades` (
  `cara37consec` INT(11) NOT NULL,
  `cara37id` INT(11) NOT NULL DEFAULT '0',
  `cara37tipodisc` INT(11) NULL DEFAULT '0',
  `cara37activa` VARCHAR(1) NULL DEFAULT NULL,
  `cara37orden` INT(11) NULL DEFAULT '0',
  `cara37nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`cara37id`),
  UNIQUE INDEX `cara37discapacidades_id` (`cara37consec` ASC) VISIBLE,
  INDEX `fk_cara37discapacidades_cara36tipodisc1_idx` (`cara37tipodisc` ASC) VISIBLE,
  CONSTRAINT `fk_cara37discapacidades_cara36tipodisc1`
    FOREIGN KEY (`cara37tipodisc`)
    REFERENCES `unadsys`.`cara36tipodisc` (`cara36id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`cara38talentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`cara38talentos` (
  `cara38consec` INT(11) NOT NULL,
  `cara38id` INT(11) NOT NULL DEFAULT '0',
  `cara38activa` VARCHAR(1) NULL DEFAULT NULL,
  `cara38orden` INT(11) NULL DEFAULT '0',
  `cara38nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`cara38id`),
  UNIQUE INDEX `cara38talentos_id` (`cara38consec` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`core09programa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`core09programa` (
  `core09codigo` INT(11) NOT NULL,
  `core09id` INT(11) NOT NULL DEFAULT '0',
  `core09nombre` VARCHAR(250) NULL DEFAULT NULL,
  `core09idescuela` INT(11) NULL DEFAULT '0',
  `core09iddirector` INT(11) NULL DEFAULT '0',
  `core09idversionactual` INT(11) NULL DEFAULT '0',
  `core09activo` VARCHAR(1) NULL DEFAULT 'S',
  `core09idtipocaracterizacion` INT(11) NULL DEFAULT '0',
  `cara09codsnies` VARCHAR(50) NULL DEFAULT '',
  `cara09nivelformacion` INT(11) NULL DEFAULT '0',
  `core09codgrados` INT(11) NULL DEFAULT '0',
  `core09titulohombres` VARCHAR(100) NULL DEFAULT NULL,
  `core09titulomujeres` VARCHAR(100) NULL DEFAULT NULL,
  `core09idtipopractica` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`core09id`),
  UNIQUE INDEX `core09programa_id` (`core09codigo` ASC) VISIBLE,
  INDEX `fk_core09programa_cara11tipocaract1_idx` (`core09idtipocaracterizacion` ASC) VISIBLE,
  CONSTRAINT `fk_core09programa_cara11tipocaract1`
    FOREIGN KEY (`core09idtipocaracterizacion`)
    REFERENCES `unadsys`.`cara11tipocaract` (`cara11id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`core12escuela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`core12escuela` (
  `core12codigo` INT(11) NOT NULL,
  `core12id` INT(11) NOT NULL DEFAULT '0',
  `core12nombre` VARCHAR(100) NULL DEFAULT NULL,
  `core12iddecano` INT(11) NULL DEFAULT '0',
  `core12idadministrador` INT(11) NULL DEFAULT '0',
  `core12tieneestudiantes` VARCHAR(1) NULL DEFAULT 'S',
  `core12idrespcursocomun` INT(11) NULL DEFAULT '0',
  `core12sigla` VARCHAR(20) NULL DEFAULT '',
  `core12identidad` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`core12id`),
  UNIQUE INDEX `core12escuela_id` (`core12codigo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`core16actamatricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`core16actamatricula` (
  `core16peraca` INT(11) NOT NULL,
  `core16tercero` INT(11) NOT NULL,
  `core16idprograma` INT(11) NOT NULL DEFAULT '0',
  `core16parametros` VARCHAR(250) NULL DEFAULT NULL,
  `core16idzona` INT(11) NULL DEFAULT '0',
  `core16idcead` INT(11) NULL DEFAULT '0',
  `core16idescuela` INT(11) NULL DEFAULT '0',
  `core16fecharecibido` INT(11) NULL DEFAULT '0',
  `core16minrecibido` INT(11) NULL DEFAULT '0',
  `core16procesado` INT(11) NULL DEFAULT '0',
  `core16numcursos` INT(11) NULL DEFAULT '0',
  `core16numaprobados` INT(11) NULL DEFAULT '0',
  `core16promedio` DECIMAL(15,2) NULL DEFAULT '0.00',
  `core16origen` INT(11) NULL DEFAULT '0',
  `core16nuevo` INT(11) NULL DEFAULT '0',
  `core16proccarac` INT(11) NULL DEFAULT '0',
  `core16procagenda` INT(11) NULL DEFAULT '0',
  `core16idconsejero` INT(11) NULL DEFAULT '0',
  `core16errormatricula` INT(11) NULL DEFAULT '0',
  `core16erroragenda` INT(11) NULL DEFAULT '0',
  `core16estado` INT(11) NULL DEFAULT '0',
  `core16aplazados` VARCHAR(250) NULL DEFAULT '',
  `core16cancelados` VARCHAR(250) NULL DEFAULT '',
  `core16fechamatricula` INT(11) NULL DEFAULT '0',
  `core16paraseguimiento` INT(11) NULL DEFAULT '0',
  `core16tipomatricula` INT(11) NULL DEFAULT '0',
  `core16idconvenio` INT(11) NULL DEFAULT '0',
  `core16edad` INT(11) NULL DEFAULT '0',
  `core16idcaracterizacion` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`core16idprograma`),
  UNIQUE INDEX `core16actamatricula_id` (`core16peraca` ASC, `core16tercero` ASC) VISIBLE,
  INDEX `fk_core16actamatricula_unad24sede1_idx` (`core16idcead` ASC) VISIBLE,
  INDEX `fk_core16actamatricula_unad23zona1_idx` (`core16idzona` ASC) VISIBLE,
  INDEX `fk_core16actamatricula_core12escuela1_idx` (`core16idescuela` ASC) VISIBLE,
  INDEX `fk_core16actamatricula_core30estadomatricula1_idx` (`core16estado` ASC) VISIBLE,
  CONSTRAINT `fk_core16actamatricula_exte02per_aca1`
    FOREIGN KEY (`core16peraca`)
    REFERENCES `unadsys`.`exte02per_aca` (`exte02id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_core16actamatricula_unad24sede1`
    FOREIGN KEY (`core16idcead`)
    REFERENCES `unadsys`.`unad24sede` (`unad24id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_core16actamatricula_unad23zona1`
    FOREIGN KEY (`core16idzona`)
    REFERENCES `unadsys`.`unad23zona` (`unad23id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_core16actamatricula_core12escuela1`
    FOREIGN KEY (`core16idescuela`)
    REFERENCES `unadsys`.`core12escuela` (`core12id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_core16actamatricula_core30estadomatricula1`
    FOREIGN KEY (`core16estado`)
    REFERENCES `unadsys`.`core30estadomatricula` (`core30id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`core30estadomatricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`core30estadomatricula` (
  `core30id` INT(11) NOT NULL,
  `core30nombre` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`core30id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`exte02per_aca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`exte02per_aca` (
  `exte02id` INT(11) NOT NULL,
  `exte02nombre` VARCHAR(100) NULL DEFAULT '',
  `exte02titulo` VARCHAR(250) NULL DEFAULT NULL,
  `exte02tipoperiodo` INT(11) NULL DEFAULT '0',
  `exte02diasactividades` INT(11) NULL DEFAULT '0',
  `exte02disponibleagendas` VARCHAR(1) NULL DEFAULT NULL,
  `exte02vigente` VARCHAR(1) NULL DEFAULT NULL,
  `exte02rutaagendas` VARCHAR(250) NULL DEFAULT NULL,
  `exte02permiteditaragenda` VARCHAR(1) NULL DEFAULT NULL,
  `exte02controlarNAVs` VARCHAR(1) NULL DEFAULT 'N',
  `exte02previo1` INT(11) NULL DEFAULT '0',
  `exte02previo2` INT(11) NULL DEFAULT '0',
  `exte02descripcionperaca` TEXT NULL DEFAULT NULL,
  `exte02fechainslab` VARCHAR(10) NULL DEFAULT '00/00/0000',
  `ext02fechafinlab` VARCHAR(10) NULL DEFAULT '00/00/0000',
  `ext02fechainssalidas` VARCHAR(10) NULL DEFAULT '00/00/0000',
  `ext02fechafinsalidas` VARCHAR(10) NULL DEFAULT '00/00/0000',
  `ext02ofertalaboratorios` VARCHAR(1) NULL DEFAULT 'N',
  `exte02fechalimgrupos` INT(11) NULL DEFAULT '0',
  `exte02contgrupos` INT(11) NULL DEFAULT '0',
  `exte02solicitante` INT(11) NULL DEFAULT '0',
  `exte02ofertacursos` VARCHAR(1) NULL DEFAULT NULL,
  `exte02ofertafechatope` INT(11) NULL DEFAULT '0',
  `exte02oferfechatopecancela` INT(11) NULL DEFAULT '0',
  `exte02fechainimatricula` INT(11) NULL DEFAULT '0',
  `exte02fechafinmatricula` INT(11) NULL DEFAULT '0',
  `exte02fechadevolderpec` INT(11) NULL DEFAULT '0',
  `exte02fechainducciones` INT(11) NULL DEFAULT '0',
  `exte02fechafinactiniciales` INT(11) NULL DEFAULT '0',
  `exte02fechatopeoil` INT(11) NULL DEFAULT '0',
  `exte02fechafinactfinales` INT(11) NULL DEFAULT '0',
  `exte02fechatopecalifhabilita` INT(11) NULL DEFAULT '0',
  `exte02fechatopeevaldocente` INT(11) NULL DEFAULT '0',
  `exte02idciclo` INT(11) NULL DEFAULT '0',
  `exte02fechatopetablero` INT(11) NULL DEFAULT '0',
  `exte02saltardobleaut` INT(11) NULL DEFAULT '0',
  `exte02peracadiplomados` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`exte02id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`unad05perfiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`unad05perfiles` (
  `unad05id` INT(11) NOT NULL,
  `unad05nombre` VARCHAR(100) NULL DEFAULT NULL,
  `unad05aplicativo` INT(11) NULL DEFAULT '0',
  `unad05reservado` VARCHAR(1) NULL DEFAULT 'N',
  `unad05delegable` VARCHAR(1) NULL DEFAULT 'N',
  PRIMARY KEY (`unad05id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`unad18pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`unad18pais` (
  `unad18codigo` VARCHAR(3) NOT NULL,
  `unad18nombre` VARCHAR(50) NULL DEFAULT NULL,
  `unad18sufijo` VARCHAR(5) NULL DEFAULT NULL,
  `unad18imgbandera` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`unad18codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`unad19depto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`unad19depto` (
  `unad19codigo` VARCHAR(5) NOT NULL,
  `unad19nombre` VARCHAR(50) NULL DEFAULT NULL,
  `unad19codpais` VARCHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`unad19codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`unad20ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`unad20ciudad` (
  `unad20codigo` VARCHAR(8) NOT NULL,
  `unad20nombre` VARCHAR(50) NULL DEFAULT NULL,
  `unad20codpais` VARCHAR(3) NULL DEFAULT NULL,
  `unad20coddepto` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`unad20codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`unad21estadocivil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`unad21estadocivil` (
  `unad21codigo` VARCHAR(1) NOT NULL,
  `unad21id` INT(11) NOT NULL DEFAULT '0',
  `unad21nombre` VARCHAR(50) NULL DEFAULT NULL,
  `unad21predet` VARCHAR(1) NULL DEFAULT NULL,
  `unad21orden` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`unad21id`),
  UNIQUE INDEX `unad21estadocivil_id` (`unad21codigo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`unad23zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`unad23zona` (
  `unad23codigo` INT(11) NOT NULL,
  `unad23id` INT(11) NOT NULL DEFAULT '0',
  `unad23nombre` VARCHAR(100) NULL DEFAULT NULL,
  `unad23conestudiantes` VARCHAR(1) NULL DEFAULT 'S',
  `unad23sigla` VARCHAR(20) NULL DEFAULT '',
  PRIMARY KEY (`unad23id`),
  UNIQUE INDEX `unad23zona_id` (`unad23codigo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `unadsys`.`unad24sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unadsys`.`unad24sede` (
  `unad24codigo` INT(11) NOT NULL,
  `unad24id` INT(11) NOT NULL DEFAULT '0',
  `unad24idzona` INT(11) NULL DEFAULT '0',
  `unad24nombre` VARCHAR(100) NULL DEFAULT NULL,
  `unad24codpais` VARCHAR(3) NULL DEFAULT NULL,
  `unas24coddepto` VARCHAR(5) NULL DEFAULT NULL,
  `unad24codciudad` VARCHAR(8) NULL DEFAULT NULL,
  `unad24idclase` INT(11) NULL DEFAULT '0',
  `unad24prefijoconsec` VARCHAR(20) NULL DEFAULT NULL,
  `unad24codigoryc` INT(11) NULL DEFAULT '0',
  `unad24activa` VARCHAR(1) NULL DEFAULT 'S',
  PRIMARY KEY (`unad24id`),
  UNIQUE INDEX `unad24sede_id` (`unad24codigo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
